---
title: "heatmap"
author: "Xintao Ding"
date: "11/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(plotly)
library(hrbrthemes)
set.seed(20191130)

pilot <- read_csv("./data/pilot.csv")
heatmap <- pilot %>% 
  filter(do_boro != "Unknown") %>% 
  select (do_boro, pu_hour) %>% 
  group_by(do_boro, pu_hour) %>% 
  count() %>% 
  group_by(do_boro) %>% 
  mutate( 
    total = sum(n)
    ) %>% 
   mutate(percent = round((n/total)*100,1))


```


```{r}
plot <- heatmap %>% 
  mutate(text = str_c("Pick Up Time: ", pu_hour , "\nDrop Off Borough: ", do_boro, "\nTrip Percentage:", percent)) %>%
  ggplot(aes(x = pu_hour, y = do_boro, fill = percent, text= text)) +
    geom_tile() +
    labs(x = "Pick Up Hour", y = "Drop-off Borough") + 
    theme_ipsum()
ggplotly(plot, tooltip = "text")
  
```

```{r}
# circular plot
circular <- heatmap %>% 
  select(do_boro, pu_hour, percent) %>% 
  mutate(individual = percent,
         group = pu_hour,
         value1 = "Manhattan",
         value2 = "Bronx", 
         value3 = "Staten Island",
         value4 = "Queens", 
         vaue5 = "Brooklyn",
         value6 = "EWR")
circular <- circular %>% 
  gather(key = "observation", value = "value",-c(1,2))


```

