---
title: "regression analysis"
output: github_document
---

```{r message=FALSE}
library(tidyverse)
library(ggplot2)

pilot = read.csv("./data/pilot.csv")
taxi_zone_lookup = read.csv("./data/taxi_zone_lookup.csv")
weather_nyc_2018 = read.csv("./data/weather_nyc_2018.csv")


  
reg_sample = pilot %>% 
  mutate(
    duration = case_when(
    pu_date != do_date ~ do_min - pu_min + (60 *(do_hour - pu_hour + 24)),
    pu_date == do_date ~ do_min - pu_min + (60 *(do_hour - pu_hour) )

  ),
      tip_percent = tip_amount/fare_amount
  ) %>% 
  filter(fare_amount != 0,
         tip_amount != 0)

reg_plot = reg_sample %>% 
  sample_frac(size = 0.1, replace = FALSE) %>% 
  filter(fare_amount != 0,
         tip_amount != 0,
         fare_amount != 52 #We find that there might be an entry error since all records that fare_amount is 52 have different distance and duration#
         ) 

reg_plot %>% 
  ggplot(aes(x = trip_distance, y = fare_amount)) +
  geom_point()



```



```{r}
reg_plot %>% 
  filter(duration <= 360) %>% 
  ggplot(aes(x = duration, y = fare_amount)) +
  geom_point()
```



```{r}
tip_plot = reg_sample %>% 
  filter(payment_type == 1, do_boro == 'Manhattan', pu_boro == 'Manhattan', do_zone != 'Unknown', pu_zone != 'Unknown') %>% 
mutate(do_zone = forcats::fct_reorder(do_zone, tip_percent),
       pu_zone = forcats::fct_reorder(pu_zone, tip_percent)) %>% 
  drop_na(do_zone, pu_zone)

tip_plot %>% 
    ggplot(aes(x = do_zone, y = tip_percent,color = do_zone)) +
  geom_boxplot(na.rm = TRUE, outlier.size = 0.1) +
  scale_y_continuous(
    limits = c(0,0.4)
  ) +
  theme(axis.text.x = element_text(angle = 70, hjust = 1), 
        legend.position = "none") +
  viridis::scale_color_viridis(discrete = TRUE)

```

```{r}

tip_plot %>% 
    ggplot(aes(x = pu_zone, y = tip_percent, color = pu_zone)) +
  geom_boxplot(na.rm = TRUE, outlier.size = 0.1) +
  scale_y_continuous(
    limits = c(0,0.4)
  ) +
  theme(axis.text.x = element_text(angle = 70, hjust = 1),
        legend.position = "none") +
  viridis::scale_color_viridis(discrete = TRUE)
```

```{r}
label_data <- tip_plot %>% 
  distinct(pu_zone) %>% 
  mutate(id = seq(1,64), 
         individual = pu_zone, 
         value = sample(0, 1), 64, replace = FALSE)

number_of_bar <- nrow(label_data)
angle <-  90 - 360 * (label_data$id-0.5) /number_of_bar
      
 
# calculate the alignment of labels: right or left
label_data$hjust<-ifelse( angle < -90, 1, 0)
 
# flip angle BY to make them readable
label_data$angle<-ifelse(angle < -90, angle+180, angle)

```


```{r}
p <- ggplot(tip_plot, aes(x=pu_zone, y=tip_percent)) +
  geom_bar(stat = "identity", fill = alpha("skyblue", 0.7)) +
ylim(-100, 120) +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-1,4), "cm")
  ) +
  coord_polar(start = 0) +
geom_text(data=label_data, aes(x=id, y = value, label= individual, hjust=hjust), color="black", fontface="bold",alpha=0.6, size=2.5, angle= label_data$angle, inherit.aes = FALSE ) 
  
p



```

```{r}
do_label_data <- tip_plot %>% 
  distinct(do_zone) %>% 
  mutate(id = seq(1,66), 
         individual = do_zone, 
         value = sample(0, 1), 66, replace = FALSE)

number_of_bar <- nrow(do_label_data)
angle <-  90 - 360 * (do_label_data$id-0.5) /number_of_bar
do_label_data$hjust<-ifelse( angle < -90, 1, 0)
 
# flip angle BY to make them readable
do_label_data$angle<-ifelse(angle < -90, angle+180, angle)

p <- ggplot(tip_plot, aes(x=do_zone, y=tip_percent)) +
  geom_bar(stat = "identity", fill = alpha("skyblue", 0.7)) +
ylim(-100, 120) +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-1,4), "cm")
  ) +
  coord_polar(start = 0) +
geom_text(data=do_label_data, aes(x=id, y = value, label= individual, hjust=hjust), color="black", fontface="bold",alpha=0.6, size=2.5, angle= do_label_data$angle, inherit.aes = FALSE ) 
  
p

```