---
title: "Tip Manhattan"
output: html_document
---

## Cab Tipping in Manhattan

We are curious what's tipping cab drivers is like in Manhattan, where supposedly the most cab services are called.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(ggplot2)
library(plotly)

pilot = read.csv("./data/pilot.csv")
taxi_zone_lookup = read.csv("./data/taxi_zone_lookup.csv")
weather_nyc_2018 = read.csv("./data/weather_nyc_2018.csv")

```

```{r echo = FALSE}
 boxplot <- pilot %>%
  filter(fare_amount != 0,
         fare_amount != 52 #We find that there might be an entry error since all records that fare_amount is 52 have different distance and duration#
         ) %>% 
  mutate(
    duration = case_when(
    pu_date != do_date ~ do_min - pu_min + (60 *(do_hour - pu_hour + 24)),
    pu_date == do_date ~ do_min - pu_min + (60 *(do_hour - pu_hour) )

  ),
      tip_percent = tip_amount/fare_amount
  )
```



```{r echo = FALSE}
tip_plot <-  boxplot %>% 
  filter(payment_type == 1, do_boro == 'Manhattan', pu_boro == 'Manhattan', do_zone != 'Unknown', pu_zone != 'Unknown') %>% 
  mutate(do_zone = forcats::fct_reorder(do_zone, tip_percent),
       pu_zone = forcats::fct_reorder(pu_zone, tip_percent)) %>% 
  drop_na(do_zone, pu_zone)
```

## Drop-off Zone
```{r echo = FALSE}
# plotly for do_zone
f1 <- list(
  family = "Arial, sans-serif",
  size = 18,
  color = "grey"
)
f2 <- list(
  family = "Old Standard TT, serif",
  size = 14,
  color = "black"
)
a <- list(
  title = "Tip Percentage",
  titlefont = f1,
  showticklabels = TRUE,
  tickangle = 45,
  tickfont = f2,
  exponentformat = "E",
  range = c(0,2)
)



b <- list(
  title = "Manhanttan Neighborhoods",
  titlefont = f1, 
  showticklabels = TRUE,
  tickangle = 45,
  tickfont = f2,
  exponntformat = "E"
)
tip_plot %>% 
  mutate(do_zone = forcats::fct_reorder(do_zone, tip_percent),
       pu_zone = forcats::fct_reorder(pu_zone, tip_percent),
       do_median = median(tip_percent),
       text = str_c("Drop Off Zone: ", do_zone , "\nTip Percent: ", tip_percent, "\nMedian Percentage:", do_median) )%>% 
  drop_na(do_zone, pu_zone) %>% 
  plot_ly(y = ~tip_percent, color = ~do_zone, text = ~text, type = "box",  colors = "Set2") %>% 
  layout(xaxis = b, yaxis = a)
```

## Pick up Zone
```{r echo = FALSE}
tip_plot %>% 
  mutate(do_zone = forcats::fct_reorder(do_zone, tip_percent),
       pu_zone = forcats::fct_reorder(pu_zone, tip_percent),
       pu_median = median(tip_percent),
       text = str_c("Pick Up Zone: ", do_zone , "\nTip Percent: ", tip_percent, "\nMedian Percentage:", pu_median) )%>% 
  drop_na(do_zone, pu_zone) %>% 
  plot_ly(y = ~tip_percent, color = ~pu_zone, type = "box", colors = "Set2") %>% 
  layout(xaxis = b, yaxis = a)
```


```{r include = FALSE}

do_plot <- tip_plot %>%
  mutate(do_median = median(tip_percent)) %>% 
  mutate(text = str_c("Drop Off Zone: ", do_zone , "\nTip Percent: ", tip_percent, "\nMedian Percentage:", tip_percent)) %>%
    ggplot(aes(x = do_zone, y = tip_percent,color = do_zone)) +
  geom_boxplot(na.rm = TRUE, outlier.size = 0.00001) +
  scale_y_continuous(
    limits = c(0,0.4)
  ) +
  theme(axis.text.x = element_text(angle = 70, hjust = 1), 
        legend.position = "none") +
  viridis::scale_color_viridis(discrete = TRUE)  

ggplotly(do_plot, tooltip = "text")

pu_plot <- tip_plot %>% 
    ggplot(aes(x = pu_zone, y = tip_percent, color = pu_zone)) +
  geom_boxplot(na.rm = TRUE, outlier.size = 0.1) +
  scale_y_continuous(
    limits = c(0,0.4)
  ) +
  theme(axis.text.x = element_text(angle = 70, hjust = 1),
        legend.position = "none") +
  viridis::scale_color_viridis(discrete = TRUE)
ggplotly(pu_plot, tooltip = "text")
```



