---
title: "weather and drive amount"
author: "Yuqing Xue"
date: "11/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gganimate)
library(ggplot2)
```

read in data
```{r}
pilot=read_csv(file = "./data/pilot.csv")
```
plot
O
```{r}
 plot_df=pilot%>%
  mutate(
  average_temp=(tmin+tmax)/2)

cab=pilot%>%
  group_by(month)%>%count(pu_date)%>%
  mutate(daily_drive=n)%>%
  ungroup(month)

```

join dataset
```{r}
plot_data = 
  left_join(plot_df, cab, by = c("month","pu_date"))%>%
  select(month, pu_date,average_temp, daily_drive,prcp)%>%
  mutate(month=as.factor(month),
         month=recode_factor(month, '1'="January", '2'="Feburary",'3'="March",'4'='April','5'='May','6'='June','7'='July','8'='August','9'='September','10'='October','11'='November','12'='December'))


```

```{r}
weather_drive=plot_data%>%
  ggplot(aes(x=average_temp, y=daily_drive, frame_vars(month)))+
  geom_point(aes(size=prcp,colour = month))+
   labs(title = 'Month: {closest_state}',
       x = 'Daily average temperature for year 2018', 
       y = 'Daily drive amount',
       colour = 'Month',
       size='precipitation'
       ) +
  transition_states(month,2,1)+
  enter_appear()+
  exit_fade()
   
animate(weather_drive, duration=7)
```

precipitaiton and drive amout 
```{r}
precipitation=
  left_join(pilot, cab, by = c("month","pu_date"))%>%
  select(month, pu_date, prcp, daily_drive)%>%
  mutate(month=as.factor(month),
         month=recode_factor(month, '1'="January", '2'="Feburary",'3'="March",'4'='April','5'='May','6'='June','7'='July','8'='August','9'='September','10'='October','11'='November','12'='December'))

  
```

making plot
```{r}
prcp_drive=precipitation%>%
  ggplot(aes(x=prcp, y=daily_drive, frame_vars(month)))+
  geom_point(aes(colour = month))+
   labs(title = 'Month: {closest_state}',
       x = 'Daily precipitation for year 2018', 
       y = 'Daily drive amount',
       colour = 'Month'
       ) +
  transition_states(month,2,1)+
  enter_appear()+
  exit_fade()
   
animate(prcp_drive, duration=7)
```
```

 
